name: I'm Crhan
markdown: redcarpet
lsi: false
pygments: true


permalink: /:year/:month/:title
assets: /assets

paginate: 10
paginate_path: "page:num"

production_url: "http://blog.crhan.com/"

disqus:
  shortname: crhan

google_analytics:
  id: "UA-23112018-7"
  domain: "crhan.com"

author:
  name: "ruohan.chen 陈若涵"
  job: "SA@Alibaba-inc"
  email:
    show_name: "墨泪"
    address: "ruohan.chen@alibaba-inc.com"
    subject: "Hi crhan"
  github: "crhan"
  twitter: "ruohanc"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
